site_name: HH. Martelaren van Gorcum
theme:
  name: material
  language: nl
  palette:
    primary: blue grey
    accent: red
  features:
    - navigation.tabs
  #   - toc.integrate

  font:
    text: Roboto
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    admonition:
      note: fontawesome/solid/music

site_url: ""
use_directory_urls: false

nav:
  - Home: index.md

  - Berichten:
      - Overzicht: berichten/index.md

  - Artikelen:
      - Overzicht: artikelen/index.md

  - Onze parochie:
      - Overzicht: onzeparochie.md

      - Vieren:
          - Samen vieren: parochie/vieren/index.md
          - Biechten: parochie/vieren/biechten.md
          - Dagelijkse Mis: parochie/vieren/dagelijkse-mis.md
          - Dopen: parochie/vieren/dopen.md
          - Trouwen: parochie/vieren/trouwen.md
          - Uitvaarten: parochie/vieren/uitvaarten.md
          - Ziekenzalving: parochie/vieren/ziekenzalving.md

      - Leren:
          - Samen leren: parochie/leren/index.md
          - Alpha cursus: parochie/leren/#de-alphacursus
          - Catholicism: parochie/leren#catholicism
          - katholiek leven: parochie/leren#katholiek-leven

      - Dienen:
          - Samen dienen: parochie/dienen/index.md
          - Voedselbank: parochie/dienen#inzameling-voor-de-voedselbank
          - Parochiële Caritas Instelling: parochie/dienen#parochiele-caritas-instelling-pci

      - Bidden:
          - Samen bidden: parochie/bidden/index.md
          - De rozenkrans: parochie/bidden/rozenkrans.md
          - Geheimen van de rozenkrans: parochie/bidden/rozenkrans.html#geheimen-van-de-rozenkrans
          - Gebed tot de aartsengel Michaël: parochie/bidden#gebed-tot-de-aartsengel-michael
          - Gebed tot de Heilige Geest: parochie/bidden#gebed-tot-de-heilige-geest
          - Gebedsoefeningen: parochie/bidden#gebedsoefeningen
          
      - Gemeenschap:
          - Onze gemeenschap: parochie/gemeenschap/index.md
          - Katholiek worden: parochie/gemeenschap#katholiek-worden
          - Koffie na de Mis: parochie/gemeenschap#koffie-na-de-mis
          - Berichten: berichten/index.md
          - RK jongerenkoor Tutti: parochie/gemeenschap#krk-jongerenkoor-tutti
          - RK koor Intermezzo: parochie/gemeenschap#rk-koor-intermezzo

      - Roosters:
          - Overzicht: parochie/roosters/index.md
          - Crèche zondagsmis: parochie/roosters/creche-zondagsmis.md
          - Koffieschenkrooster: parochie/roosters/koffieschenkrooster.md
          - Korenrooster: parochie/roosters/korenrooster.md
          - Kostersrooster: parochie/roosters/kostersrooster.md
          - Lectorenrooster: parochie/roosters/lectorenrooster.md
          - Misdienaarsrooster: parochie/roosters/misdienaarsrooster.md




  - In Memoriam: inmemoriam.md
  - Over ons: overons.md
  - Contact: contact.md



extra:
  social:
    - icon: fontawesome/regular/envelope
      link: /contact.html
      target: _self
    - icon: fontawesome/solid/phone
      link: tel:+31623902455
    - icon: fontawesome/brands/whatsapp
      link: https://whatsapp.com/channel/0029VbBZTv79xVJiB1zM7f3n
  generator: false

copyright: Parochie van de Heilige Martelaren van Gorcum • Wijnkoperstraat 4 • 4204 HK • Gorinchem

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/custom.js

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

plugins:
  - search
  - blog:
      blog_dir: berichten
      post_date_format: full
      post_url_format: "{slug}"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      archive_name: Archief
      archive_date_format: MMMM yyyy
      authors_file: ".authors.yml"
      archive: false
      blog_toc: true
      categories: false
      post_readtime: false
  - blog:
      blog_dir: artikelen
      post_date_format: full
      post_url_format: "{slug}"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      archive_name: Archief
      archive_date_format: MMMM yyyy
      authors_file: ".authors.yml"
      archive: false
      blog_toc: true
